import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/providers/toaster-provider";
import { AuthProvider } from "@/context/authContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Choose weights you want
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <AuthProvider>
          <div className="h-full">
            <ToastProvider />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
